// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1H4hs7rHtupaqwnuIVldEdHV0f0Ld-U8',
    appId: '1:500686808538:web:0f746357215b871e6d4ce3',
    messagingSenderId: '500686808538',
    projectId: 'news-app-172b5',
    authDomain: 'news-app-172b5.firebaseapp.com',
    storageBucket: 'news-app-172b5.firebasestorage.app',
    measurementId: 'G-2S56CWTS07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS45GAtEMkbOHODXrzJ0ir5yB6M4UMh8U',
    appId: '1:500686808538:android:d1a174073ea6ab016d4ce3',
    messagingSenderId: '500686808538',
    projectId: 'news-app-172b5',
    storageBucket: 'news-app-172b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdf993j6xh0kJrGZq_v9YnFI1Kgsz2YM0',
    appId: '1:500686808538:ios:dce4a5d2d185f0666d4ce3',
    messagingSenderId: '500686808538',
    projectId: 'news-app-172b5',
    storageBucket: 'news-app-172b5.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdf993j6xh0kJrGZq_v9YnFI1Kgsz2YM0',
    appId: '1:500686808538:ios:dce4a5d2d185f0666d4ce3',
    messagingSenderId: '500686808538',
    projectId: 'news-app-172b5',
    storageBucket: 'news-app-172b5.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1H4hs7rHtupaqwnuIVldEdHV0f0Ld-U8',
    appId: '1:500686808538:web:bcc88ffee6c7df9f6d4ce3',
    messagingSenderId: '500686808538',
    projectId: 'news-app-172b5',
    authDomain: 'news-app-172b5.firebaseapp.com',
    storageBucket: 'news-app-172b5.firebasestorage.app',
    measurementId: 'G-HV3CECZXM2',
  );

}